django_tutorial/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('tracker/', include('money_tracker.urls')),

]

money_tracker/urls.py
from django.urls import path
from money_tracker.views import show_tracker
from money_tracker.views import create_transaction
from money_tracker.views import show_xml #sesuaikan dengan nama fungsi yang dibuat
from money_tracker.views import show_json #sesuaikan dengan nama fungsi yang dibuat
from money_tracker.views import show_xml_by_id, show_json_by_id #sesuaikan dengan nama fungsi yang dibuat
from money_tracker.views import register #sesuaikan dengan nama fungsi yang dibuat
from money_tracker.views import login_user #sesuaikan dengan nama fungsi yang dibuat
from money_tracker.views import logout_user #sesuaikan dengan nama fungsi yang dibuat
from money_tracker.views import modify_transaction
from money_tracker.views import delete_transaction

from money_tracker.views import create_transaction_ajax



app_name = 'money_tracker'

urlpatterns = [
    path('', show_tracker, name='show_tracker'),
    path('create', create_transaction, name='create_transaction'),
    path('json/', show_json, name='show_json'), #sesuaikan dengan nama fungsi yang dibuat
    path('xml/', show_xml, name='show_xml'), #sesuaikan dengan nama fungsi yang dibuat
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),

    path('register/', register, name='register'), #sesuaikan dengan nama fungsi yang dibuat

    path('login/', login_user, name='login'), #sesuaikan dengan nama fungsi yang dibuat


    path('logout/', logout_user, name='logout'), #sesuaikan dengan nama fungsi yang dibuat

   
    path('modify/<int:id>', modify_transaction, name='modify_transaction'), #sesuaikan dengan nama fungsi yang dibuat

        
    path('delete/<int:id>', delete_transaction, name='delete_transaction'), #sesuaikan dengan nama fungsi yang dibuat

    path('create-ajax/', create_transaction_ajax, name='create_transaction_ajax'),






]

money_tracker/models.py
from django.db import models

# Create your models here.


TYPE_CHOICES = [
    ('Pengeluaran', 'Pengeluaran'),
    ('Pemasukan', 'Pemasukan')
]

class TransactionRecord(models.Model):
    name = models.CharField(max_length=50)
    type = models.CharField(max_length=20, choices=TYPE_CHOICES)
    amount = models.IntegerField()
    date = models.DateTimeField(auto_now_add=True)
    description = models.TextField()

money_tracker/forms.py
from django.forms import ModelForm
from money_tracker.models import TransactionRecord

class TransactionRecordForm(ModelForm):
    class Meta:
        model = TransactionRecord
        fields = ["name", "type", "amount", "description"]

money_tracker/views.py
from django.http import HttpResponse
from django.core import serializers
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseRedirect
from money_tracker.forms import TransactionRecordForm
from django.urls import reverse
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages


from django.shortcuts import render

from money_tracker.models import TransactionRecord
from django.contrib.auth import authenticate, login

@csrf_exempt
def create_transaction_ajax(request):
# create object of form
    form = TransactionRecordForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        form.save()
        data = TransactionRecord.objects.last()

        # parsing the form data into json
        result = {
            'id':data.id,
            'name':data.name,
            'type':data.type,
            'amount':data.amount,
            'date':data.date,
            'description':data.description,
        }
        return JsonResponse(result)
    context = {'form': form}
    return render(request, "create_transaction.html", context)

def create_transaction(request):
    form = TransactionRecordForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        form.save()
        return HttpResponseRedirect(reverse('money_tracker:show_tracker'))

    context = {'form': form}
    return render(request, "create_transaction.html", context)


def show_xml(request):
    data = TransactionRecord.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = TransactionRecord.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_by_id(request,id):
    data = TransactionRecord.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")


def show_xml_by_id(request,id):
    data = TransactionRecord.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")


# Create your views here.

@login_required(login_url='/tracker/login/')
def show_tracker(request):
    transaction_data = TransactionRecord.objects.all()
    context = {
        'list_of_transactions': transaction_data,
        'name': request.user.username,
        'last_login': request.COOKIES['last_login'],
    }

    return render(request, "tracker.html", context)

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('money_tracker:login')

    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)  # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("money_tracker:show_tracker"))  # membuat response
            response.set_cookie('last_login',
                                str(datetime.datetime.now()))  # membuat cookie last_login dan menambahkannya ke dalam response
            return response



        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)


def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('money_tracker:login'))
    response.delete_cookie('last_login')
    return response

def modify_transaction(request, id):
    # Get data berdasarkan ID
    transaction = TransactionRecord.objects.get(pk = id)

    # Set instance pada form dengan data dari transaction
    form = TransactionRecordForm(request.POST or None, instance=transaction)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('money_tracker:show_tracker'))

    context = {'form': form}
    return render(request, "modify_transaction.html", context)

def delete_transaction(request, id):
    # Get data berdasarkan ID
    transaction = TransactionRecord.objects.get(pk = id)
    # Hapus data
    transaction.delete()
    # Kembali ke halaman awal
    return HttpResponseRedirect(reverse('money_tracker:show_tracker'))

money_tracker/templates/create_transaction.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<h1>Tambah Transaksi Baru</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Tambah"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

money_tracker/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>

            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    Belum mempunyai akun? <a href="{% url 'money_tracker:register' %}">Buat Akun</a>

</div>

{% endblock content %}

money_tracker/templates/modify_transaction.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<h1>Ubah Data Transaksi</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Ubah"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

money_tracker/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">

    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

money_tracker/templates/tracker.html
{% extends 'base.html' %}

{% block content %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<nav class="navbar navbar-expand-lg bg-light">
  
    <div class="container-fluid" style="background-color: rgba(210, 85, 215, 0.614);">
      <a class="navbar-brand" href="#" >Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Dropdown
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="#">{{name}}</a></li>
              <li><a class="dropdown-item" href="#"></a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled">Disabled</a>
          </li>
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>
  
<h5 style="color:rgb(119, 9, 209);background-color: rgb(0, 140, 255);">Nama: </h5>
<p style="color: rgb(119, 9, 209);background-color: rgb(0, 140, 255);">{{name}}</p>

<table>
    <tr>
        <th>Nama</th>
        <th>Jenis</th>
        <th>Jumlah</th>
        <th>Tanggal</th>
        <th>Deskripsi</th>
        <th>Aksi</th>
    </tr>

      {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
      {% for transaction in list_of_transactions %}
          <tr>
              <td>{{transaction.name}}</td>
              <td>{{transaction.type}}</td>
              <td>{{transaction.amount}}</td>
              <td>{{transaction.date}}</td>
              <td>{{transaction.description}}</td>
              <td>
                  <a href="{% url 'money_tracker:modify_transaction' transaction.pk %}">
                      <button>
                          Ubah
                      </button>
                  </a>

                <a href="{% url 'money_tracker:delete_transaction' transaction.pk %}">
                    <button>
                        Hapus
                    </button>
                </a>
              
              </td>
          </tr>
      {% endfor %}
  </table>


<h5>Sesi terakhir login: {{ last_login }}</h5>



<br>

<a href="{% url 'money_tracker:logout' %}">
    <button>
        Logout
    </button>
</a>


<a href="{% url 'money_tracker:create_transaction' %}">
    <button>
        Transaksi Baru
    </button>
</a>
<header></header>

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
{% block meta %}
{% endblock meta %}
</head>

<body>
{% block content %}
{% endblock content %}
</body>

</html>